[package]
name = "rust-ecs"
version = "1.0.0"
edition = "2021"
authors = [ "Lut99" ]
description = "A (simple) Entity Component System in Rust that may be used for multiple projects."

[dependencies]
log = "0.4.16"
parking_lot = "0.12.1"
